config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'
  
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories

    validates :title, presence: true, length: {minimum: 3, maximum: 100}
    validates :description, presence: true, length: {minimum: 5, maximum: 300}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :article_categories
    has_many :articles, through: :article_categories

    validates :name, presence: true, uniqueness: true, length: {minimum: 3, maximum: 25}
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase}
  has_many :articles, dependent: :destroy

  validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 25}
  # Constant
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def require_user
        if !helpers.logged_in?
            flash[:danger] = "You must be logged in to perform that action"
            redirect_to root_path
        end
    end
    
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def show
        @article = Article.find(params[:id])
    end

    def index
        @articles = Article.paginate(page: params[:page], per_page: 3)
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        @article.user = helpers.current_user
        # render plain: @article.inspect
        # byebug
        if @article.save
            flash[:notice] = "Article was created successfully."
            redirect_to @article
        else
            render 'new'
        end
    end

    def edit

    end

    def update
        if @article.update(article_params)
            flash[:notice] = "Article was updated successfully"
            redirect_to @article
        else
            render "edit"
        end
    end

    def destroy
        @article.destroy
        redirect_to articles_path
    end

    private

    def set_article
        @article = Article.find(params[:id])
    end


    def article_params
        params.require(:article).permit(:title, :description, category_ids: [])
    end

    def require_same_user
        if helpers.current_user != @article.user && !current_user.admin?
            flash[:danger] = "You can edit or delete only your own articles"
            redirect_to root_path
        end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:index, :show]
    before_action :set_category, only: [:edit, :update, :destroy]
    
    def index
        @categories = Category.paginate(page: params[:page], per_page: 3)
    end

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:notice] = "Category was created successfully"
            redirect_to categories_path
        else
            render 'new'
        end
    end

    def show
        @category = Category.find(params[:id])
        @category_articles = @category.articles.paginate(page: params[:page], per_page: 2)
    end

    def edit
        
    end

    def update
        if @category.update(category_params)
            flash[:notice] = "Category updated successfully"
            redirect_to category_path(@category)
        else
            render 'edit'
        end
    end

    private

    def set_category
        @category = Category.find(params[:id])
    end

    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if !helpers.logged_in? || (helpers.logged_in? && !helpers.current_user.admin?)
            flash[:danger] = "Only admins can perform that action"
            redirect_to categories_path
        end
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to articles_path if helpers.logged_in?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Logged in successfully"
            redirect_to user
        else
            flash.now[:alert] = "There was something wrong with your login details"
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged out"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]  
  before_action :require_user, except: [:index, :show, :new, :create]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 3)
  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 3)
  end

  def new
      @user = User.new

  end

  def create
      @user = User.new(user_params)
      if (@user.save)
          flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, you have successfully sign up."
          session[:user_id] = @user.id
          redirect_to user_path(@user)
      else
          render 'new'
      end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account information was successfully updated"
      redirect_to users_path
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    flash[:danger] = "User and all articles created by the user have been deleted"
    redirect_to users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
      params.require(:user).permit(:username, :email, :password)
  end

  def require_same_user
    if helpers.current_user != @user and !helpers.current_user.admin?
        flash[:danger] = "You can only edit your own profile"
        redirect_to root_path
    end
  end

  def require_admin
    if helpers.logged_in? and !helpers.current_user.admin?
      flash[:danger] = "Only admin users can perform that action"
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = {size: 80})
        email_address = user.email
        hash = Digest::MD5.hexdigest(email_address)
        size = options[:size]
        gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"

        image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
    end

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_articles.html.erb
<% obj.each do |article| %>
<div class="row mt-4 justify-content-md-center">
    <div class="col-8">
        <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header font-italic">
                By <%= link_to article.user.username.capitalize, article.user %>
            </div>
            <div class="card-body">
                <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success"%></h5>
                <p class="card-text"><%= truncate(article.description, length: 100)%></p>
                <% if article.categories.any?%>
                    <p>Categories: <%= render article.categories %></p>
                <%end%>
                <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
                <% if logged_in? && (current_user == article.user || current_user.admin?)%>
                    <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
                    <%= link_to "Delete", article_path(article), method: :delete, class: "btn btn-outline-danger" %>
                <% end %>
            </div>
            <div class="card-footer text-muted">
                Created <%=time_ago_in_words(article.created_at)%> ago,
                edited <%=time_ago_in_words(article.updated_at)%> ago
            </div>
        </div>
    </div>
</div>
<%end%>

app/views/articles/_form.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-10">
            <%= render 'shared/form_errors', obj: @article %>
            <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true ) do |f| %>
                <div class="form-group row">    
                    <%= f.label :title, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
                    </div>
                </div>
                <div class="form-group row">
                    <%= f.label :description, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
                    </div>
                </div>
                <div class="form-group row">
                    <%= f.label :categories, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <div class="form-check form-check-inline">
                            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
                            <% cb.label(class: "form-check-label mr-4") {cb.check_box(class: "form-check-input") + cb.text} %>
                            <%end%>
                        </div>
                    </div>
                </div>               
                <div class="form-group row justify-content-center">
                    <%= f.submit class: "btn btn-outline-light btn-lg"%>
                </div>
            <%end%>
        </div>
        <div class="mb-3"> <%= link_to "[ Cancel and return to articles listing ]", articles_path, class: "text-info" %></div>
       
    </div>
</div>

app/views/articles/_form_errors.html.erb
<% if @article.errors.any? %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the article from being saved.</h4>
    <ul>
        <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<% end %>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing All Articles</h1>
<div class="container">
    <div class="flickr_pagination">
        <%= will_paginate @articles, :container => false %>
    </div>
    <%= render 'articles', obj: @articles %>
    <div class="flickr_pagination mb-4">
        <%= will_paginate @articles, :container => false %>
    </div>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create new article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<div class="page-content">
    <h2 class="text-center mt-4"><%=@article.title%></h2>
    <div class="container">
        <div class="row mt-4 justify-content-md-center">
            <div class="col-8">
                <div class="card text-center shadow mb-5 bg-white rounded">
                    <div class="card-header font-italic">
                        By <%= @article.user.username.capitalize%>
                        <%= link_to gravatar_for(@article.user), @article.user %>
                    </div>
                    
                    <div class="card-body">
                        <div class="card-text text-left"><%= simple_format(@article.description)%></div>
                        <% if @article.categories.any?%>
                            <p class="text-left">Categories: <%= render @article.categories %></p>
                        <%end%>
                        <% if logged_in? && (current_user == @article.user || current_user.admin?)%>
                            <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
                            <%= link_to "Delete", article_path(@article), method: :delete, class: "btn btn-outline-danger" %>
                        <%end%>
                    </div>
                    <div class="card-footer text-muted">
                        Created <%=time_ago_in_words(@article.created_at)%> ago,
                        edited <%=time_ago_in_words(@article.updated_at)%> ago
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/categories/_category.html.erb
<span class="badge badge-pill badge-success mr-3"><%= link_to category.name, category_path(category) %> &nbsp;</span>

app/views/categories/_form.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-10">
            <%= render 'shared/form_errors', obj: @category %>
            <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true ) do |f| %>
                <div class="form-group row">    
                    <%= f.label :name, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a category name" %>
                    </div>
                </div>
                <div class="form-group row justify-content-center">
                    <%= f.submit class: "btn btn-outline-light btn-lg"%>
                </div>
            <%end%>
        </div>
        <div class="mb-3"> <%= link_to "[ Cancel and return to articles listing ]", articles_path, class: "text-info" %></div>
       
    </div>
</div>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit category <%= @category.name %></h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">List categories</h1>

<div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
</div>

<% @categories.each do |category| %>
<div class="row mt-4 justify-content-md-center">
    <div class="col-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header font-italic">
                <%= link_to category.name, category_path(category) %>
                
            </div>
            <div class="card-body">
                <small><%= pluralize(category.articles.count, "articles") %></small>
            </div>
            <div class="card-footer text-muted">
                Created <%=time_ago_in_words(category.created_at)%> ago
            </div>
        </div>
    </div>
</div>
<%end%>

<div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">New category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %></h1>
<% if logged_in? && current_user.admin? %>
    <p class="text-center"><%= link_to "Edit Category", edit_category_path, class: "btn btn-outline-info" %></p>
<%end%>
<div class="container">
    <div class="flickr_pagination">
        <%= will_paginate @category_articles, :container => false %>
    </div>
    <%= render 'articles/articles', obj: @category_articles %>
    <div class="flickr_pagination mb-4">
        <%= will_paginate @category_articles, :container => false %>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small>Copyright &copy; Your Website</small>
    </div>
  </footer>

app/views/layouts/_messages.html.erb
<% if flash.any? %>
<div class="container">
    <% flash.each do |name, msg| %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <%= msg %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    <% end %>
</div>
<%end%>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Alpha Bloggers", users_path, class: "nav-link" %>
        </li>
        <% if !logged_in? %>
          <li class="nav-item">
            <%= link_to "Articles", articles_path, class: "nav-link" %>
          </li>
        <%end%>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Categories
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown2">
            <%= link_to "List Categories", categories_path, class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <% Category.all.each do |category| %>
              <%= link_to "#{category.name}", category_path(category), class: "dropdown-item" %>
            <%end%>
            <% if logged_in? %>
              <div class="dropdown-divider"></div>
              <%= link_to "New category", new_category_path, class: "dropdown-item" %>
            <%end%>
          </div>
        </li>        
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Articles
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "List Articles", articles_path, class: "dropdown-item" %>
              <%= link_to "New Article", new_article_path, class: "dropdown-item" %>
            </div>
          </li>
          <li class="nav-item">
            <%= link_to current_user.admin? ? "Admin - Your profile" : "Your profile", user_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", logout_path, method: :delete, class: "nav-link" %>
          </li>
        <%else%>
          <li class="nav-item">
            <%= link_to "Login", login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", signup_path, class: "nav-link" %>
          </li>
        <%end%>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>

<%= link_to "Articles listing", articles_path %>|
<%= link_to "Home page", root_path %>

app/views/pages/home.html.erb
<div class="container mt-4" >
    <div class="jumbotron text-center text-white">
        <h1 class="display-4">Alpha Blog</h1>
        <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <%= link_to "Sign Up!", signup_path, class: "btn btn-success btn-lg" %>
</div>

app/views/shared/_form_errors.html.erb
<% if obj.errors.any? %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved.</h4>
    <ul>
        <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-10">
            <%= render 'shared/form_errors', obj: @user %>
            <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true ) do |f| %>
                <div class="form-group row">    
                    <%= f.label :username, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
                    </div>
                </div>
                <div class="form-group row">
                    <%= f.label :email, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter an email" %>
                    </div>
                </div>
                <div class="form-group row">
                    <%= f.label :password, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Enter password" %>
                    </div>
                </div>                
                <div class="form-group row justify-content-center">
                    <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-outline-light btn-lg")%>
                </div>
            <%end%>
        </div>
        <div class="mb-3"> <%= link_to "[ Cancel and return to articles listing ]", articles_path, class: "text-info" %></div>
       
    </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your profile</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha Blogers</h1>

<div class="flickr_pagination mb-4">
    <%= will_paginate @users, :container => false %>
</div>

<% @users.each do |user| %>
<div class="row mt-4 justify-content-md-center">
    <div class="col-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header font-italic">
                <%= link_to user.username, user_path(user) %>
            </div>
            <div class="card-body">
                <div class="text-center mb-3"><%= link_to gravatar_for(user, size: 200), user %></div>
                <p><%= pluralize(user.articles.count, "article") %></p>
                <%= link_to "View profile", user_path(user), class: "btn btn-outline-success" %>
                <% if logged_in? && (current_user == user || current_user.admin?)%>
                    <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %>
                <%end%>
                <% if logged_in? && current_user.admin? %>
                    <%= link_to "Delete user", user_path(user), method: :delete, data: {confirm: "Are you sure you want to delete the user and all their articles?"}, class: "btn btn-outline-danger" %>
                <% end %>
            </div>
            <div class="card-footer text-muted">
                Joined <%=time_ago_in_words(user.created_at)%> ago
            </div>
        </div>
    </div>
</div>
<%end%>

<div class="flickr_pagination mb-4">
    <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Signup for Alpha Blog</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username%>'s profile</h1>
<%= gravatar_for @user, size: 200 %>
<% if logged_in? && (current_user == @user || current_user.admin?)%>
    <div class="text-center mt-4"><%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %></div>
<% end %>

<h1 class="text-center mt-4">Articles</h1>
<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/articles', obj: @articles %>

<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>